services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    #ports:
    #  - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - backend_network # Connessione esclusivamente con BE

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    #ports:
    #  - "1885:1883" # MQTT
    #  - "5672:5672" # AMQP
    #  - "15672:15672" # Management UI
    #  - "15675:15675" # MQTT over WebSocket
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq
      - ./rabbitmq/conf:/etc/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
    networks:
      - shared_network # Connessione con Kong e BE

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    #ports:
    #  - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGO_URL=mongodb://mongodb:27017/projectOne
      - MQTT_HOST=rabbitmq
      - MQTT_PORT=1883
      - MQTT_WS_PORT=15675
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    restart: unless-stopped
    networks:
      - backend_network # Connessione con Mongo
      - shared_network # Connessione con Kong e RabbitMQ
    volumes: # Necessari per permettere il 'hot-reload'
      - ./back-end:/usr/src/be # 'Linkiamo' il codice, ogni modifica fatta viene trasmessa al container subito
      - /usr/src/be/node_modules # Rimuoviamo la cartella dei moduli che verrà creata solo al build iniziale

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - frontend_network # Connessione esclusivamente con Kong
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_MQTT_HOST=localhost
      - REACT_APP_MQTT_PORT=8000 # Kong's port
      - REACT_APP_MQTT_PATH=/mqtt-ws
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    volumes: # Necessari per permettere il 'hot-reload'
      - ./front-end:/usr/src/fe # 'Linkiamo' il codice, ogni modifica fatta viene trasmessa al container subito
      - exclude:/usr/src/fe/node_modules # Rimuoviamo la cartella dei moduli che verrà creata solo al build iniziale

  # Kong services
  kong-db:
    image: postgres:13
    container_name: kong-db
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kongpass
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - kong_network # Connessione esclusiva per servizi Kong
    restart: unless-stopped

  kong-migrations:
    image: kong:latest
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
    networks:
      - kong_network # Connessione esclusiva per servizi Kong
    restart: on-failure

  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      - kong-migrations
      - kong-db
      - rabbitmq
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - "8000:8000" # Kong proxy port
      - "8001:8001" # Kong Admin API
      - "8443:8443" # Kong proxy SSL
      - "8444:8444" # Kong Admin API SSL
    networks:
      - frontend_network # Connessione con FE
      - shared_network # Connessione con RabbitMQ e BE
      - kong_network # Connessione esclusiva per servizi Kong
    restart: unless-stopped

  kong-setup:
    image: alpine:latest
    container_name: kong-setup
    depends_on:
      - kong
    volumes:
      - ./kong-setup.sh:/kong-setup.sh
    command: sh -c "apk add --no-cache curl && chmod +x /kong-setup.sh && sh /kong-setup.sh" #Aggiungiamo curl, mettiamo i permessi di esecuzione e facciamo partire lo script di inizializzazione
    networks:
      - frontend_network # Connessione con FE
      - shared_network # Connessione con BE e RabbitMQ (deve creare service e route)
      - kong_network # Connessione esclusiva per servizi Kong
    restart: on-failure

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
  shared_network:
    driver: bridge
  kong_network:
    driver: bridge

volumes:
  mongo_data:
  kong_data:
  exclude:
