services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    #command: |
    #  bash -c "
    #  rabbitmq-plugins enable rabbitmq_mqtt rabbitmq_web_mqtt &&
    #  rabbitmq-server
    #  "
    ports:
      - "1885:1883"  # MQTT
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
      - "15675:15675"  # MQTT over WebSocket
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq
      - ./rabbitmq/conf:/etc/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
    networks:
      - app_network

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
    - MONGO_URL=mongodb://mongodb:27017/projectOne
    - MQTT_HOST=rabbitmq
    - MQTT_PORT=1883
    - MQTT_WS_PORT=15675
    - RABBITMQ_USER=guest
    - RABBITMQ_PASSWORD=guest
    restart: unless-stopped
    networks:
      - app_network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app_network
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_MQTT_HOST=localhost
      - REACT_APP_MQTT_PORT=15675
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data: