services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    #command: |
    #  bash -c "
    #  rabbitmq-plugins enable rabbitmq_mqtt rabbitmq_web_mqtt &&
    #  rabbitmq-server
    #  "
    ports:
      - "1885:1883"  # MQTT
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
      - "15675:15675"  # MQTT over WebSocket
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq
      - ./rabbitmq/conf:/etc/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
    networks:
      - app_network

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
    - MONGO_URL=mongodb://mongodb:27017/projectOne
    - MQTT_HOST=rabbitmq
    - MQTT_PORT=1883
    - MQTT_WS_PORT=15675
    - RABBITMQ_USER=guest
    - RABBITMQ_PASSWORD=guest
    restart: unless-stopped
    networks:
      - app_network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app_network
    environment:
    - REACT_APP_API_URL=http://localhost:8080
    - REACT_APP_MQTT_HOST=localhost
    - REACT_APP_MQTT_PORT=8000 # Kong's port
    - REACT_APP_MQTT_PATH=/mqtt-ws
    - RABBITMQ_USER=guest
    - RABBITMQ_PASSWORD=guest
  
  # Kong services
  kong-db:
    image: postgres:13
    container_name: kong-db
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kongpass
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped
    
  kong-migrations:
    image: kong:latest
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
    networks:
      - app_network
    restart: on-failure

  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      - kong-migrations
      - kong-db
      - rabbitmq
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - "8000:8000" # Kong proxy port
      - "8001:8001" # Kong Admin API
      - "8443:8443" # Kong proxy SSL
      - "8444:8444" # Kong Admin API SSL
    networks:
      - app_network
    restart: unless-stopped
  
  kong-setup:
    image: alpine:latest
    container_name: kong-setup
    depends_on:
      - kong
    volumes:
      - ./kong-setup.sh:/kong-setup.sh
    command: sh -c "apk add --no-cache curl && chmod +x /kong-setup.sh && sh /kong-setup.sh"
    networks:
      - app_network
    restart: on-failure

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
  kong_data: